version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=url_shortner
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: url_shortner
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
